package com.oliveoa.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.oliveoa.pojo.CompanyInfo;
import com.oliveoa.pojo.DepartmentInfo;
import com.oliveoa.pojo.DutyInfo;
import com.oliveoa.pojo.EmployeeInfo;

import com.oliveoa.greendao.CompanyInfoDao;
import com.oliveoa.greendao.DepartmentInfoDao;
import com.oliveoa.greendao.DutyInfoDao;
import com.oliveoa.greendao.EmployeeInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig companyInfoDaoConfig;
    private final DaoConfig departmentInfoDaoConfig;
    private final DaoConfig dutyInfoDaoConfig;
    private final DaoConfig employeeInfoDaoConfig;

    private final CompanyInfoDao companyInfoDao;
    private final DepartmentInfoDao departmentInfoDao;
    private final DutyInfoDao dutyInfoDao;
    private final EmployeeInfoDao employeeInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        companyInfoDaoConfig = daoConfigMap.get(CompanyInfoDao.class).clone();
        companyInfoDaoConfig.initIdentityScope(type);

        departmentInfoDaoConfig = daoConfigMap.get(DepartmentInfoDao.class).clone();
        departmentInfoDaoConfig.initIdentityScope(type);

        dutyInfoDaoConfig = daoConfigMap.get(DutyInfoDao.class).clone();
        dutyInfoDaoConfig.initIdentityScope(type);

        employeeInfoDaoConfig = daoConfigMap.get(EmployeeInfoDao.class).clone();
        employeeInfoDaoConfig.initIdentityScope(type);

        companyInfoDao = new CompanyInfoDao(companyInfoDaoConfig, this);
        departmentInfoDao = new DepartmentInfoDao(departmentInfoDaoConfig, this);
        dutyInfoDao = new DutyInfoDao(dutyInfoDaoConfig, this);
        employeeInfoDao = new EmployeeInfoDao(employeeInfoDaoConfig, this);

        registerDao(CompanyInfo.class, companyInfoDao);
        registerDao(DepartmentInfo.class, departmentInfoDao);
        registerDao(DutyInfo.class, dutyInfoDao);
        registerDao(EmployeeInfo.class, employeeInfoDao);
    }
    
    public void clear() {
        companyInfoDaoConfig.clearIdentityScope();
        departmentInfoDaoConfig.clearIdentityScope();
        dutyInfoDaoConfig.clearIdentityScope();
        employeeInfoDaoConfig.clearIdentityScope();
    }

    public CompanyInfoDao getCompanyInfoDao() {
        return companyInfoDao;
    }

    public DepartmentInfoDao getDepartmentInfoDao() {
        return departmentInfoDao;
    }

    public DutyInfoDao getDutyInfoDao() {
        return dutyInfoDao;
    }

    public EmployeeInfoDao getEmployeeInfoDao() {
        return employeeInfoDao;
    }

}
