package com.oliveoa.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.oliveoa.pojo.DepartmentInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DEPARTMENT_INFO".
*/
public class DepartmentInfoDao extends AbstractDao<DepartmentInfo, Long> {

    public static final String TABLENAME = "DEPARTMENT_INFO";

    /**
     * Properties of entity DepartmentInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property Dcid = new Property(1, String.class, "dcid", false, "DCID");
        public final static Property Dpid = new Property(2, String.class, "dpid", false, "DPID");
        public final static Property Id = new Property(3, String.class, "id", false, "ID");
        public final static Property Name = new Property(4, String.class, "name", false, "NAME");
        public final static Property Telephone = new Property(5, String.class, "telephone", false, "TELEPHONE");
        public final static Property Fax = new Property(6, String.class, "fax", false, "FAX");
        public final static Property Orderby = new Property(7, int.class, "orderby", false, "ORDERBY");
        public final static Property Createtime = new Property(8, String.class, "createtime", false, "CREATETIME");
        public final static Property Updatetime = new Property(9, String.class, "updatetime", false, "UPDATETIME");
    }


    public DepartmentInfoDao(DaoConfig config) {
        super(config);
    }
    
    public DepartmentInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DEPARTMENT_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"DCID\" TEXT," + // 1: dcid
                "\"DPID\" TEXT," + // 2: dpid
                "\"ID\" TEXT," + // 3: id
                "\"NAME\" TEXT," + // 4: name
                "\"TELEPHONE\" TEXT," + // 5: telephone
                "\"FAX\" TEXT," + // 6: fax
                "\"ORDERBY\" INTEGER NOT NULL ," + // 7: orderby
                "\"CREATETIME\" TEXT," + // 8: createtime
                "\"UPDATETIME\" TEXT);"); // 9: updatetime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DEPARTMENT_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DepartmentInfo entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String dcid = entity.getDcid();
        if (dcid != null) {
            stmt.bindString(2, dcid);
        }
 
        String dpid = entity.getDpid();
        if (dpid != null) {
            stmt.bindString(3, dpid);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(4, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String telephone = entity.getTelephone();
        if (telephone != null) {
            stmt.bindString(6, telephone);
        }
 
        String fax = entity.getFax();
        if (fax != null) {
            stmt.bindString(7, fax);
        }
        stmt.bindLong(8, entity.getOrderby());
 
        String createtime = entity.getCreatetime();
        if (createtime != null) {
            stmt.bindString(9, createtime);
        }
 
        String updatetime = entity.getUpdatetime();
        if (updatetime != null) {
            stmt.bindString(10, updatetime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DepartmentInfo entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String dcid = entity.getDcid();
        if (dcid != null) {
            stmt.bindString(2, dcid);
        }
 
        String dpid = entity.getDpid();
        if (dpid != null) {
            stmt.bindString(3, dpid);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(4, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String telephone = entity.getTelephone();
        if (telephone != null) {
            stmt.bindString(6, telephone);
        }
 
        String fax = entity.getFax();
        if (fax != null) {
            stmt.bindString(7, fax);
        }
        stmt.bindLong(8, entity.getOrderby());
 
        String createtime = entity.getCreatetime();
        if (createtime != null) {
            stmt.bindString(9, createtime);
        }
 
        String updatetime = entity.getUpdatetime();
        if (updatetime != null) {
            stmt.bindString(10, updatetime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DepartmentInfo readEntity(Cursor cursor, int offset) {
        DepartmentInfo entity = new DepartmentInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // dcid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // dpid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // id
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // telephone
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // fax
            cursor.getInt(offset + 7), // orderby
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // createtime
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // updatetime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DepartmentInfo entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDcid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDpid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTelephone(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setFax(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setOrderby(cursor.getInt(offset + 7));
        entity.setCreatetime(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setUpdatetime(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DepartmentInfo entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DepartmentInfo entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DepartmentInfo entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
